<?php

namespace AppBundle\Repository;

/**
 * CommentPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
