<?php

namespace AppBundle\Repository;

/**
 * CommentVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
