<?php

namespace AppBundle\Repository;

/**
 * FacePlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacePlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
