<?php

namespace AppBundle\Repository;

/**
 * MediaCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
