<?php

namespace AppBundle\Repository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{

	public function findPhotosByEvent(\AppBundle\Entity\Event $event)
    {
        return $this->createQueryBuilder('m')
        	->where('m.type = :type')
            ->andWhere('m.event = :eventid')
            ->setParameter('eventid', $event->getId())
            ->setParameter('type', "pho")
            ->getQuery();
    }
}
