<?php

namespace AppBundle\Repository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{

	public function findPhotosByEvent(\AppBundle\Entity\Event $event)
    {
        return $this->createQueryBuilder('p')
            ->where('p.event = :eventid')
            ->setParameter('eventid', $event->getId())
            ->getQuery();
    }

}
