<?php

namespace AppBundle\Repository;

/**
 * UserEventViewedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEventViewedRepository extends \Doctrine\ORM\EntityRepository
{
}
