<?php

namespace AppBundle\Repository;

/**
 * VideoFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoFileRepository extends \Doctrine\ORM\EntityRepository
{
}
