app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Security
logout:
    path: /logout

# SonataAdminBundle
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin