# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.event:
        class: AppBundle\Admin\EventAdmin
        arguments: [~, AppBundle\Entity\Event, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Events }
    admin.theme:
        class: AppBundle\Admin\ThemeAdmin
        arguments: [~, AppBundle\Entity\Theme, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Themes }