# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  # Twig Extentions
  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension}

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension}

  twig.extension.date:
    class: Twig_Extensions_Extension_Date
    arguments:
      - "@translator.default" 
    tags:
      - { name: twig.extension}

  # Sonata Admin Bundle
  admin.event:
    class: AppBundle\Admin\EventAdmin
    arguments: [~, AppBundle\Entity\Event, ~]
    tags:
        - { name: sonata.admin, manager_type: orm, label: Events }
  
  admin.theme:
    class: AppBundle\Admin\ThemeAdmin
    arguments: [~, AppBundle\Entity\Theme, ~]
    tags:
        - { name: sonata.admin, manager_type: orm, label: Themes }

  admin.face:
    class: AppBundle\Admin\FaceAdmin
    arguments: [~, AppBundle\Entity\Face, ~]
    tags:
        - { name: sonata.admin, manager_type: orm, label: Faces }

  admin.user:
    class: AppBundle\Admin\UserAdmin
    arguments: [~, AppBundle\Entity\User, ~]
    tags:
        - { name: sonata.admin, manager_type: orm, label: Users }